#!/bin/bash

# http://finviz.com/screener.ashx?v=111&f=sh_avgvol_u1000,sh_curvol_o2000
# array=( AAPL ABBV ABT ABX ACN ADBE AEM AET AGN AGNC AIG ALTR ALU AMGN AMTD AMX AMZN APA APC ARCP ATHL ATML ATVI AUY AVNW AXP BA BAC BAX BBBY BBD BBT BCS BEAM BEE BHI BIDU BK BMY BP BRCD BRCM BSX BWP BX C CBS CCK CELG CI CIG CIT CMCSA CMG CNP CNQ COF COG COP CSCO CSX CTRX CTSH CVS CVX CZZ DAL DCT DD DEJ DFS DHR DIS DISH DOW DRYS DTV DVN EBAY ECA EGO EIX EMC EOG ESRX ESV EXC F FB FCS FCX FEYE FITB FLEX FNFG FOXA GCI GE GFI GG GGB GGP GLW GM GNW GOOG GOOGL GPK GPS GRT GS HAL HBAN HD HES HIMX HON HPQ HTZ IBM IDRA INCY INTC IR ISR ITUB JNJ JPM KEY KGC KKR KMI KO LBTYA LKQ LLTC LLY LNKD LOW LUK LUV LVS LYB LYG M MA MAT MBT MCD MDLZ MDT MET MGI MO MPEL MRK MRO MS MSFT NBR NE NEM NKE NLY NOK NOV NTAP ONNN ORCL OXY PAL PBR PBR-A PDS PEP PFE PG PHM PM POT PPL PSX PTEN QCOM RAD RAI RF SBUX SCHW SFUN SID SLB SLM SNH SNV SO SPLK SRC SSN STI STLD SWK SWN SYMC SYY T TEVA TGT TLM TMUS TRQ TSM TWO TWX TXN TYC UAL UEPS UNH UNP UPS USB V VALE VIP VLO VOD VZ WAG WDAY WFC WFM WFT WLP WMB WMT WRES WY XEL XOM XRX YHOO YNDX ZLCS ZTS  )
array=( ibb bdsi vicl tsla myl zgnx plug ormp arwr fslr erbb gss heb mstx pal cpst cvm dvax fst gale gern gnk rsh aci alu amd mnga wpwr tgro cbrx rosg)
for i in "${array[@]}"
do
    # python draw.py $i 300 5
    python draw.py $i 180 3
done


